name: habit_tracker
description: "A Habit Tracker App."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  date_picker_plus: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  test: ^1.25.15

flutter:
  uses-material-design: true

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Black.ttf
      - asset: assets/fonts/Lato-Light.ttf
      - asset: assets/fonts/Lato-Thin.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
